spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/ManagementSystem
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs


server:
  port: 8888

jwt:
  auth:
    converter:
      resource-id: ManagementSystem-rest-api1
      principle-attribute: preferred_username



